import type { ScanResult, ModuleInfo, SymbolInfo } from './types'
import { VERSION } from '../../version'

export class KnowledgeRenderer {
  /**
   * Render .ai/knowledge/INDEX.md
   */
  renderIndex(result: ScanResult): string {
    const shortHash = result.commitHash ?? 'unknown'
    const lines: string[] = [
      '<!-- AUTO-GENERATED: safe to edit, do not delete header -->',
      '# Codebase Knowledge Index',
      `> Auto-generated by dotai knowledge scan | v${VERSION}`,
      `> Last scanned: ${result.scannedAt} | Commit: ${shortHash}`,
      `> Total files: ${result.totalFiles} across ${result.modules.length} modules`,
      '',
      '## Module Map',
      '',
      '| Module | Path | Files | Key Exports | Depends On |',
      '|--------|------|-------|-------------|------------|',
    ]

    for (const mod of result.modules) {
      const keyExports = this.getKeyExports(mod, 4)
      const deps = mod.dependencies.length > 0 ? mod.dependencies.join(', ') : '—'
      lines.push(`| ${mod.name} | ${mod.path} | ${mod.files.length} | ${keyExports} | ${deps} |`)
    }

    lines.push('', '## Dependency Graph', '')
    lines.push('<!-- Read this to understand what depends on what before making changes -->')
    for (const mod of result.modules) {
      if (mod.dependencies.length > 0) {
        lines.push(`- **${mod.name}** → ${mod.dependencies.join(', ')}`)
      }
    }

    lines.push('', '## Quick Reference', '')
    lines.push('<!-- Auto-populated from module scans -->')
    lines.push('| Symbol | Module | Kind |')
    lines.push('|--------|--------|------|')

    for (const mod of result.modules) {
      const exportedSymbols = this.getAllExportedSymbols(mod)
      for (const sym of exportedSymbols.slice(0, 10)) {
        lines.push(`| ${sym.name} | ${mod.name} | ${sym.kind} |`)
      }
    }

    lines.push('')
    return lines.join('\n')
  }

  /**
   * Render .ai/knowledge/modules/<name>.md
   */
  renderModule(module: ModuleInfo): string {
    const shortHash = module.commitHash ?? 'unknown'
    const lines: string[] = [
      '<!-- AUTO-GENERATED: safe to edit, do not delete header -->',
      `# ${module.name}`,
      `> Auto-generated | Last updated: ${module.lastScanned} | Commit: ${shortHash}`,
      `> Path: \`${module.path}\``,
      '',
    ]

    // Files table
    lines.push('## Files')
    lines.push('| File | Lines | Key Symbols |')
    lines.push('|------|-------|-------------|')
    for (const file of module.files) {
      const symbols = file.topLevelSymbols
        .filter((s) => s.isExported)
        .map((s) => s.name)
        .slice(0, 5)
        .join(', ')
      const fileName = file.relativePath.split('/').pop() ?? file.relativePath
      lines.push(`| ${fileName} | ${file.lineCount} | ${symbols || '—'} |`)
    }

    // Key Symbols by kind
    const allSymbols = this.getAllExportedSymbols(module)
    const classes = allSymbols.filter((s) => s.kind === 'class')
    const functions = allSymbols.filter((s) => s.kind === 'function' || s.kind === 'method')
    const interfaces = allSymbols.filter((s) => s.kind === 'interface' || s.kind === 'type')
    const enums = allSymbols.filter((s) => s.kind === 'enum')
    const variables = allSymbols.filter((s) => s.kind === 'variable')

    lines.push('', '## Key Symbols', '')
    if (classes.length > 0) {
      lines.push('### Classes')
      for (const s of classes) {
        const deco = s.decorators?.length ? ` — ${s.decorators.map((d) => `@${d}`).join(', ')}` : ''
        lines.push(`- \`${s.name}\`${deco}`)
      }
      lines.push('')
    }
    if (functions.length > 0) {
      lines.push('### Functions / Methods')
      for (const s of functions) {
        const sig = s.signature ? `\`${s.signature}\`` : `\`${s.name}\``
        lines.push(`- ${sig}`)
      }
      lines.push('')
    }
    if (interfaces.length > 0) {
      lines.push('### Interfaces / Types')
      lines.push(`- ${interfaces.map((s) => `\`${s.name}\``).join(', ')}`)
      lines.push('')
    }
    if (enums.length > 0) {
      lines.push('### Enums')
      lines.push(`- ${enums.map((s) => `\`${s.name}\``).join(', ')}`)
      lines.push('')
    }
    if (variables.length > 0) {
      lines.push('### Variables / Constants')
      lines.push(`- ${variables.map((s) => `\`${s.name}\``).join(', ')}`)
      lines.push('')
    }

    // Dependencies
    lines.push('## Dependencies')
    const importedFrom = module.dependencies.length > 0
      ? module.dependencies.map((d) => `\`${d}\``).join(', ')
      : '—'
    const importedBy = module.dependents.length > 0
      ? module.dependents.map((d) => `\`${d}\``).join(', ')
      : '—'
    lines.push(`- **Imports from**: ${importedFrom}`)
    lines.push(`- **Imported by**: ${importedBy}`)

    // Patterns and Gotchas — skeletons for human/agent editing
    lines.push('', '## Patterns Observed')
    lines.push('<!-- dotai auto-detects and humans/agents append here -->')
    lines.push('', '## Gotchas & Edge Cases')
    lines.push('<!-- Agents and humans append here — do NOT delete these -->')
    lines.push('')

    return lines.join('\n')
  }

  /**
   * Render initial .ai/knowledge/patterns.md (skeleton only)
   */
  renderPatterns(): string {
    return [
      '<!-- AUTO-GENERATED: safe to edit, do not delete header -->',
      '# Code Patterns',
      '',
      '> Recurring patterns discovered in this codebase.',
      '> Added by: dotai scanner, AI agents (/learn command), and humans.',
      '',
      '<!-- Add patterns below. Format:',
      '## Pattern Name',
      '**Where used**: files or modules',
      '**Description**: what the pattern is',
      '**Example**: brief code example if helpful',
      '-->',
      '',
    ].join('\n')
  }

  /**
   * Render initial .ai/knowledge/gotchas.md (skeleton only)
   */
  renderGotchas(): string {
    return [
      '<!-- AUTO-GENERATED: safe to edit, do not delete header -->',
      '# Gotchas & Edge Cases',
      '',
      '> Things that are NOT obvious from reading the code.',
      '> Added by: dotai scanner, AI agents (/learn command), and humans.',
      '',
      '<!-- Add gotchas below. Format:',
      '## Gotcha Title',
      '**Found in**: file or module',
      '**Symptom**: what goes wrong if you violate this',
      '**Rule**: what to always/never do',
      '-->',
      '',
    ].join('\n')
  }

  /**
   * Render initial .ai/knowledge/changelog.md (skeleton only)
   */
  renderChangelog(): string {
    return [
      '<!-- AUTO-GENERATED: safe to edit, do not delete header -->',
      '# Knowledge Changelog',
      '',
      '> Automatically updated by dotai on each git commit (when hook is installed).',
      '> Also updated manually via `dotai knowledge update`.',
      '',
      '<!-- Entries are prepended (newest first) -->',
      '',
    ].join('\n')
  }

  /**
   * Append a changelog entry (called on incremental update).
   */
  appendChangelogEntry(
    existing: string,
    changedFiles: string[],
    commitHash: string,
    commitMessage: string
  ): string {
    const timestamp = new Date().toISOString()
    const fileList = changedFiles.slice(0, 10).map((f) => `  - ${f}`).join('\n')
    const truncated = changedFiles.length > 10
      ? `\n  - ... and ${changedFiles.length - 10} more`
      : ''

    const entry = [
      `## ${timestamp.split('T')[0]} — ${commitHash}`,
      `**${commitMessage}**`,
      '',
      `Changed ${changedFiles.length} file(s):`,
      fileList + truncated,
      '',
    ].join('\n')

    // Prepend after the header comment marker
    const marker = '<!-- Entries are prepended (newest first) -->'
    const markerIdx = existing.indexOf(marker)
    if (markerIdx >= 0) {
      const insertAt = markerIdx + marker.length
      return existing.slice(0, insertAt) + '\n\n' + entry + existing.slice(insertAt)
    }

    // Fallback: append at end
    return existing + '\n' + entry
  }

  /**
   * Merge existing module content: preserve Gotchas and Patterns sections.
   */
  mergeModuleContent(existingContent: string, newRendered: string): string {
    const existingGotchas = this.extractSection(existingContent, '## Gotchas & Edge Cases')
    const existingPatterns = this.extractSection(existingContent, '## Patterns Observed')

    let result = newRendered

    if (existingPatterns) {
      result = result.replace(
        /## Patterns Observed\n<!-- dotai auto-detects and humans\/agents append here -->/,
        existingPatterns
      )
    }

    if (existingGotchas) {
      result = result.replace(
        /## Gotchas & Edge Cases\n<!-- Agents and humans append here — do NOT delete these -->/,
        existingGotchas
      )
    }

    return result
  }

  private extractSection(content: string, heading: string): string | null {
    const idx = content.indexOf(heading)
    if (idx < 0) return null

    // Find the next ## heading (or end of file)
    const nextHeadingIdx = content.indexOf('\n## ', idx + heading.length)
    const section = nextHeadingIdx >= 0
      ? content.slice(idx, nextHeadingIdx).trimEnd()
      : content.slice(idx).trimEnd()

    // Only return if there's actual content beyond the heading and comment
    const lines = section.split('\n').filter((l) => l.trim() && !l.startsWith('<!--'))
    if (lines.length <= 1) return null

    return section
  }

  private getKeyExports(module: ModuleInfo, limit: number): string {
    const symbols: string[] = []
    for (const file of module.files) {
      for (const sym of file.topLevelSymbols) {
        if (sym.isExported && symbols.length < limit) {
          symbols.push(sym.name)
        }
      }
    }
    return symbols.length > 0 ? symbols.join(', ') : '—'
  }

  private getAllExportedSymbols(module: ModuleInfo): SymbolInfo[] {
    return module.files.flatMap((f) =>
      f.topLevelSymbols.filter((s) => s.isExported)
    )
  }
}
